### PR TITLE
docs: fix documentation error

### PR DESCRIPTION
**Pull request by fuxingZhang**
Fix the documentation and code inconsistencies caused by the following commit. 
> https://github.com/prometheus-community/windows_exporter/commit/e9c594473c0b9b794422e8314bd58f92bcc5c2e6

### CODE REVIEW

**Comment by fuxingZhang** [comment]
The commit modifies the listening address, not the configuration file.

image

image

**Comment by breed808** [comment]
That's correct, but your change introduces a second `--web.config.file`  entry in the README:
Screenshot_20230312_092815

**Comment by fuxingZhang** [comment]
Sorry for my carelessness

**Comment by fuxingZhang** [comment]
@breed808 I've modified the commit.

**Review by breed808 — APPROVED** [review]
Looks good, thanks for updating it :+1:

**Pull request merged**
