### PR TITLE
Synchronize common files from prometheus/prometheus

### PR DESCRIPTION
**Pull request by prombot**
Propagating changes from prometheus/prometheus default branch.

### CODE REVIEW

**Comment by carlpett** [comment]
@SuperQ @brian-brazil Should the common sync be enabled on this repo?
The code of conduct should, but do we want to do a relicensing?

**Comment by SuperQ** [comment]
Good question on the license change. The CNCF requires that Prometheus projects be Apache. But I don't know if this applies to community.

It looks like I also need to make adjustments to the sync script.

**Comment by SuperQ** [comment]
FYI, I'm updating the [sync policy](https://github.com/prometheus/prometheus/pull/7433) to exclude LICENSE files that aren't already Apache. Once that's merged, we can close this PR and the bot will open a new ones without that change.

**Comment by SuperQ** [comment]
New policy is merged, going to close this and wait for the next cron job.

**Pull request closed without merging**
