### PR TITLE
Fix some promtool warnings

### PR DESCRIPTION
**Pull request by mjtrangoni**
Hi @breed808 @carlpett,

This fix all `non-histogram and non-summary metrics should not have "_count" suffix` issues reported by `promtool`. See #659.

NOTE: This must be noted as breaking changes in the CHANGELOG for the next version. 

Just let me know if I should proceed with the other reported issues.

### CODE REVIEW

**Review by carlpett — COMMENTED** [review]
Looks good to me as such, but to read naturally, the "subject" of the metrics should probably be in plural after the change. E.g. `handles`, `threads`, etc.

**Comment by breed808** [comment]
I think a `promtool` check should be added to our CI as well, at least for the default collectors.

**Comment by mjtrangoni** [comment]
@carlpett good point! I´ve made all metric plural now. PTAL.

**Review by carlpett — APPROVED** [review]
Thanks!

**Pull request merged**
