### PR TITLE
Update collector.service.md

### PR DESCRIPTION
**Pull request by louij2**
Added more details for monitoring multiple services.

### CODE REVIEW

**Comment by carlpett** [comment]
Hi @louij2,
Thanks for helping to improve the docs! We need to ask you to sign the DCO before merging this, however. There's quite good instructions on the "Details" link above if you are unsure how to, or let us know if anything is not working.

**Comment by louij2** [comment]
> Hi @louij2,
> Thanks for helping to improve the docs! We need to ask you to sign the DCO before merging this, however. There's quite good instructions on the "Details" link above if you are unsure how to, or let us know if anything is not working.

Not sure how to do this with Github desktop?

**Comment by louij2** [comment]
> Hm. From what I can tell, [Github Desktop doesn't support signing off commits](https://github.com/desktop/desktop/issues/5351). That's unfortunate. Do you have the git commandline tooling installed? If so you can run
> 
> ```
> git commit --amend --no-edit --signoff
> git push --force-with-lease origin patch-1
> ```

Screenshot 2021-04-22 at 20 44 04
Sorry I don't do this often but can't get any further? Patch-1 does exist so not sure what it means.

**Comment by carlpett** [comment]
`patch-1` is the name of the branch in your fork. I wonder if you might be on the wrong branch locally? This would fix it, in that case:
```
git checkout patch-1
git reset --hard origin/patch-1
git commit --amend --no-edit --signoff
git push --force-with-lease origin patch-1
```

If that doesn't work, I'll see if we can figure out some workaround

**Comment by louij2** [comment]
> `patch-1` is the name of the branch in your fork. I wonder if you might be on the wrong branch locally? This would fix it, in that case:
> 
> ```
> git checkout patch-1
> git reset --hard origin/patch-1
> git commit --amend --no-edit --signoff
> git push --force-with-lease origin patch-1
> ```
> 
> If that doesn't work, I'll see if we can figure out some workaround

Got it working now. Guess I have to wait for someone to say yes now?

**Review by breed808 — APPROVED** [review]
Looks good! Thanks for updating the docs :+1:

**Pull request merged**
