### PR TITLE
Add HTTPS configuration

### PR DESCRIPTION
**Pull request by replay**
This PR is based on https://github.com/prometheus-community/windows_exporter/pull/693

### CODE REVIEW

**Comment by replay** [comment]
> I guess this way it could work, but it's not very nice

nvm, that interface cannot be cast in the way I tried, I'll try to find another solution

**Review by breed808 — COMMENTED** [review]
I'm also very keen to see HTTPS support in the windows_exporter, but the use of two logging libraries will cause confusion for users.
Those running the exporter from the MSI install will have most logs sent to Windows Event Log, while HTTPS-related events sent to STDOUT will be effectively dropped.

It's not a problem with an easy solution, as the `exporter-toolkit/https` library requires `go-kit/kit/log` which doesn't currently support Windows Event logging.

**Comment by replay** [comment]
> I'm also very keen to see HTTPS support in the windows_exporter, but the use of two logging libraries will cause confusion for users.
Those running the exporter from the MSI install will have most logs sent to Windows Event Log, while HTTPS-related events sent to STDOUT will be effectively dropped.

That's definitely not optimal

> It's not a problem with an easy solution, as the exporter-toolkit/https library requires go-kit/kit/log which doesn't currently support Windows Event logging.

Afaict we have the following options:

1) Use mixed loggers, which is what this PR implements, you have already pointed out the disadvantages of this.
2) Use a different HTTPS server than the one from the `exporter-toolkit`, that's what I implemented in [this PR](https://github.com/prometheus-community/windows_exporter/pull/708).
3) Update the `exporter-toolkit` and make its HTTPS server use the logger from `github.com/prometheus/common/log`, I don't know enough about that library to judge how difficult/easy that would be and whether such a change would get accepted.

**Comment by carlpett** [comment]
What I've done on the half-finished work that I mentioned in the other PR is a fourth option, namely a wrapper. I can try to get that finished tonight, since there appears to be much interest in this.

**Comment by replay** [comment]
Closing this because https://github.com/prometheus-community/windows_exporter/pull/693 has been merged

**Pull request closed without merging**
