### PR TITLE
Bump Go version from 1.13 to 1.15 for CI

### LINKED ISSUE #629: PowerRegisterSuspendResumeNotification in Docker images due to older Go version
I believe this is an artifact of https://github.com/golang/go/issues/35447, which to my understanding was fixed in either Go 1.14 or 1.15. The currently available binaries in the releases page seem to be built with Go 1.13.3 based on the `--version` output. Note also that this repro does not work on all machines. Our production Windows Kubernetes cluster can run these executables, but my local Windows 10 Pro machine cannot.

Actions:

1. Downloads `windows_exporter-0.14.0-amd64.exe` from releases
2. Launch a Docker container using `docker run --rm -it -v C:\Users\<elided>\Downloads\:c:\Downloads mcr.microsoft.com/windows/servercore:2004`
3. Run the executable

Expected: same output as running outside of the container

Actual:

```
C:\downloads>.\windows_exporter-0.14.0-amd64.exe --version
fatal error: PowerRegisterSuspendResumeNotification failure

runtime stack:
runtime.throw(0xabcb38, 0x2e)
        C:/go/src/runtime/panic.go:774 +0x79 fp=0x158fdb0 sp=0x158fd80 pc=0x4330a9
runtime.monitorSuspendResume()
        C:/go/src/runtime/os_windows.go:294 +0x1a9 fp=0x158fe50 sp=0x158fdb0 pc=0x42f209
runtime.goenvs()
        C:/go/src/runtime/os_windows.go:531 +0x1ba fp=0x158fea8 sp=0x158fe50 pc=0x42fb8a
runtime.schedinit()
        C:/go/src/runtime/proc.go:554 +0xa9 fp=0x158ff00 sp=0x158fea8 pc=0x435aa9
runtime.rt0_go(0x158ff30, 0x7ffcce5e7034, 0x158ff30, 0x0, 0x7ffcce5e7034, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/go/src/runtime/asm_amd64.s:214 +0x13d fp=0x158ff08 sp=0x158ff00 pc=0x45f33d
```

I've built the executable myself and used that in the Docker container, and it works as expected:

```
C:\downloads>.\windows_exporter.exe --version
windows_exporter, version 0.14.0-10-g8f2f9d8 (branch: master, revision: 8f2f9d83f9379136a1c148ef1c4b3bf0d50b2a6a)
  build user:       <elided>
  build date:       20201019-08:05:47
  go version:       go1.15.3
```

It would be great if the releases could be updated to use a more recent version of Go. I'm not familiar with Go CI processes in general, but if this is something you'd like a PR for, please let me know and I'll try to put something together.

### PR DESCRIPTION
**Pull request by snoyberg**
Fixes #629, by including bugfix for
https://github.com/golang/go/issues/35447

### CODE REVIEW

**Comment by carlpett** [comment]
Thanks! I downloaded the built file and noticed it is still built with Go 1.13 🤔 A took a look at the [AppVeyor docs](https://www.appveyor.com/docs/windows-images-software/#golang), and it seems the `stack` directive isn't really used any more, instead each builder image has a default version. So if I read it correctly we should instead remove the `stack`, and bump to using the `Visual Studio 2019` image?

**Comment by snoyberg** [comment]
Makes perfect sense following the charts in https://www.appveyor.com/docs/windows-images-software/#golang. I'll push an update. Thanks for checking the executable!

**Comment by snoyberg** [comment]
Sorry, the error messages about `gcc` are beyond my experience level, and I don't think I'll be able to dive in and work on this on my own. Let me know if you'd like me to close out this PR, I don't want to clutter your open PRs with something that isn't going to build.

**Comment by carlpett** [comment]
Ugh, looks like they've moved around the compilers between the versions 🤦 (We have to use CGO with a C/C++-compiler to reach into some of the container-related stuff).
I'll see if there's a simple fix.

**Comment by carlpett** [comment]
It appears the new path to put on L15 is `C:\msys64\mingw64\bin`, then it should work!

**Comment by snoyberg** [comment]
That seemed to do it, thank you! I've confirmed that the Go version is correct:

```
> .\windows_exporter-0.15.0-629-bump-go-version.1+16-386.exe --version
windows_exporter, version 0.15.0-629-bump-go-version.1+16 (branch: 629-bump-go-version, revision: f8b63bcbd9af10f89f76f5e4a373531d22eb0376)
  build user:       appveyor-vm\appveyor@appveyor-vm
  build date:       20201019-13:01:12
  go version:       go1.15.2
> .\windows_exporter-0.15.0-629-bump-go-version.1+16-amd64.exe --version
windows_exporter, version 0.15.0-629-bump-go-version.1+16 (branch: 629-bump-go-version, revision: f8b63bcbd9af10f89f76f5e4a373531d22eb0376)
  build user:       appveyor-vm\appveyor@appveyor-vm
  build date:       20201019-13:00:54
  go version:       go1.15.2
```

**Review by carlpett — APPROVED** [review]
:tada:

**Comment by snoyberg** [comment]
Thank you for the super fast feedback and guidance!

**Pull request merged**
