### PR TITLE
Add yaml for WS2022 nodes

### PR DESCRIPTION
**Pull request by vrapolinario**
Adding a yaml spec with an image supported on Windows Server 2022 nodes.

### CODE REVIEW

**Review by breed808 — COMMENTED** [review]
Thanks for submitting this. The 2022 manifest appears to be identical to the existing manifest, except for the image tag.

I don't think the level of duplication here is ideal, but the complexity of the manifests isn't enough to warrant a helm chart (not that I could support one anyway).

Do you think it would be worth updating the tag in the existing manifest?

**Comment by vrapolinario** [comment]
That would be a solution for WS2022 nodes - hopefully that's what people are using these days, but then it becomes a problem for people running WS2019, hence my proposal for a separate file.

**Comment by breed808** [comment]
Just so I understand correctly, for windows containers the image and node must match? I.E. a Windows 2019 node cannot run 2022 container images?

**Comment by vrapolinario** [comment]
That is correct. And the images are version specific.

**Comment by vrapolinario** [comment]
That is correct. And the images are version specific. More info here: https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-11

**Comment by breed808** [comment]
Thanks for enlightening me on this, I wasn't aware of the Windows container/host restrictions. If you sign the commit (to pass the DCO check) I'll get this merged.

**Comment by vrapolinario** [comment]
#sign-off

**Comment by breed808** [comment]
@vrapolinario you'll need to sign the commit with `git commit --amend --no-edit -s`. You can open the DCO details link for more info on the signing.

**Comment by vrapolinario** [comment]
Sorry for the delay - JubeCon and all. I have just signed the commit following the instructions. Apologies as my Git abilities are very limited. :)

**Review by breed808 — APPROVED** [review]
Not a problem, thanks for updating it.

**Pull request merged**
