### PR TITLE
Load config file from URL

### PR DESCRIPTION
**Pull request by DiniFarb**
As requested in #1207 I've added support for loading the config file either from a directory or a URL.

### CODE REVIEW

**Review by breed808 — COMMENTED** [review]
Thanks for submitting this! Would it be possible to include a flag allowing a user to skip TLS verification for the config file? I know some users of the exporter may have self-signed certificates in place, despite it not being best practice.

Something like this, with `insecure_skip_verify` being passed to the `NewResolver` function as a `bool` parameter:

```golang
tr := &http.Transport{
        TLSClientConfig: &tls.Config{InsecureSkipVerify: insecure_skip_verify},
    }
    client := &http.Client{Transport: tr}
    _, err := client.Get(file)
```

**Comment by DiniFarb** [comment]
Good point and it is good to have such a flag for testing purposes as well. I'll implement that. 

The flag should then be passed as an argument like:

`--config.file.skip-tls-verify=true` right? 

Or somehow passed in as a prefix or suffix in the url? Like:

config.file="[insecure_skip_verify]https://example.net/config.yaml"

**Comment by breed808** [comment]
Yes, a boolean flag would be preferable here (assuming the flag library supports that type).

**Comment by DiniFarb** [comment]
Done, now its possible to skip TLS. 
One more question though, I saw that the `--config.file` flag is not listed in the global [flags](https://github.com/prometheus-community/windows_exporter#flags) section of the readme. Wouldn't it be good to add the config flag plus the new skip TLS flag well as?

**Comment by breed808** [comment]
Sure, feel free to add it in the readme if you like.

One other thing: you'll need to sign-off the commit(s) in order to pass the CI DCO check. I can't recall if _all_ commits need to be signed or just the last, but I'd assume the worst and sign all of them.

Let me know if you need assistance with that.

**Comment by DiniFarb** [comment]
I'am not quite sure, should I use `git rebase --signoff HEAD~6` to sign commits afterwarts ?

**Comment by breed808** [comment]
Yes, the `git rebase --signoff` command should do it if the DCO check continues to fail

**Comment by breed808** [comment]
Hmm, the force push seems to have added other commits, and there's been a couple merge commits since then.
Want some assistance rebasing the feature branch? I believe I can push to it.

**Comment by DiniFarb** [comment]
Yes I have always synct the pr branch as soon as it was behind the prometheus-community:master. Shouldn't I have done that? 😬 sorry for that, and yes u should be able to push to the pr branch. Otherwise just write the rebase command I should use.

**Comment by breed808** [comment]
Syncing it with the upstream `master` branch is generally advised, the issue here is that this PR is proposing to merge your `master` branch into the `master` branch of the `windows_exporter` project, so we'd end up merging merge commits. Merges all the way down :smile:

I'll force-push to your master branch now in order to tidy the commits in this PR, once I've pushed have a review of the commits and let me know if you're happy with the result. If not I can revert the changes.

**Comment by breed808** [comment]
Commits look alright now, though the DCO check is complaining again :frowning_face: 

> Author: andreasvogt89, Committer: Ben Reedy; Expected "andreasvogt89 30302212+andreasvogt89@users.noreply.github.com", but got "Vogt Andreas, INI-MBM-BNC Andreas.Vogt3@swisscom.com"

**Comment by DiniFarb** [comment]
yes my bad, I've used the wrong account last week to sign the commits 😐 I've done it again but with the sync again I've fu* up the commit timeline again. Could you help me with the rebase ?

**Comment by breed808** [comment]
Got it, the DCO check is happy now. Have a review of the commits and let me know if you're happy with them, then I'll get this merged.

**Comment by DiniFarb** [comment]
I am very sorry for the confusion I've created here and many thx for fixing all 😊 The commits are looking very good and clean to me now 👍🏼

**Comment by breed808** [comment]
It's fine, nothing to worry about. `git` is not the easiest tool to use, especially when trying to cleanly merge changes.

**Review by breed808 — APPROVED** [review]

**Pull request merged**
