### PR TITLE
scheduled_task: Move OLE connection to collect function

### LINKED ISSUE #1425: Issue with scheduled_task
The scheduled_task returns `CO_E_NOTINITIALIZED`  when I try to use it. I think it is getting initialized in build but then uninited.  if I remove this line https://github.com/prometheus-community/windows_exporter/blob/master/pkg/collector/scheduled_task/scheduled_task.go#L130 it works as expected.

### PR DESCRIPTION
**Pull request by jkroepke**
Based on: https://github.com/influxdata/telegraf/blob/2de80263d5875531b5c39eb63c85b20109a35799/plugins/inputs/win_wmi/query.go#L77

Fixes #1425

### CODE REVIEW

**Comment by jkroepke** [comment]
@mattdurham does fix the issue on your side?

Connecting to OLE during collect should also increase the support for multiple instances and reduce the locking to an minimum.

On my local system, I do not longer had issues.

**Comment by mattdurham** [comment]
I think it should but will verify

**Comment by breed808** [comment]
@mattdurham did you manage to verify the change?

**Comment by jkroepke** [comment]
@breed808 otherwise, if you agree - take a review and merge it.

It was wrong anyways to construct the OLE init on builder func. If the issue is not resolved, feedback can be applied in https://github.com/prometheus-community/windows_exporter/issues/1425

**Review by breed808 — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
