### PR TITLE
Document expected delays in the size metrics

### PR DESCRIPTION
**Pull request by JDA88**

### CODE REVIEW

**Review by breed808 — CHANGES_REQUESTED** [review]
Looking good! Can we add a brief description to the [metric help text](https://github.com/prometheus-community/windows_exporter/blob/5b92e1bd3dd87ff691383dc66ec0c66778099490/collector/logical_disk.go#L104-L116)?

**Review by JDA88 — COMMENTED** [review]
Well, no that I don’t want but I am really struggling with GitHub

**Comment by breed808** [comment]
Does the website or Github Desktop allow you to modify the commit text?

**Comment by JDA88** [comment]
> Does the website or Github Desktop allow you to modify the commit text?

If it's possible i cant find a way to do it

**Review by breed808 — APPROVED** [review]
Looks good :thumbsup:

**Comment by JDA88** [comment]
I tryed to edit the first file again with the signoff command, doesn't look like it helped :)

**Comment by breed808** [comment]
Yeah, looks like it wants it done through the CLI: https://github.com/prometheus-community/windows_exporter/pull/846/checks?check_run_id=3761153419

**Comment by JDA88** [comment]
I currently dont have access to the CLI and it's taking way to much time for me for such a simple task.
Thanks four your help anyway 👍

**Comment by breed808** [comment]
In that case, I'll see if I can update your branch so we can merge it. Thanks anyway for trying :smiley:

**Comment by JDA88** [comment]
Done, thank you for your help

**Pull request merged**
