### PR TITLE
Add coretemp collector

### PR DESCRIPTION
**Pull request by martinlindhe**
Hello!
I have been digging around trying to get proper CPU temperature readings.

Here's what I learned:
- thermalzone collector mostly does not export anything. No driver seems to be available by default and where is even one for Intel CPU:s?
- Intel and AMD cpu:s report core temperatures in different ways. Implementations exist but most is closed source. I did find some information about how to read this, for example openhardwaremonitor (C#) has some code here: https://github.com/openhardwaremonitor/openhardwaremonitor/tree/master/Hardware/CPU
- Reading CPU temperatures directly requires program to run as Administrator, complicating setup
- Reading CPU temperatures directly requires writing a bunch of code I'm not committed enough to put more time into.

Eventually I figured out that the software Core Temp (https://www.alcpu.com/CoreTemp/) has an API of sorts, and instead built a collector directly using it.
This has the following advantages:
- no administrator required
- CoreTemp reports temperature & core load data in a uniform way for both Intel and AMD cpu:s

And the following disadvantages:
- CoreTemp must also be installed and running on the machine to monitor
- No direct golang implementation of temperature scraping
- Coretemp is not free for commercial use

And probably more I didn't think about.

Anyway, this is sort of a hack but works well and exports cpu data such as this:

```
# HELP windows_coretemp_load (Load)
# TYPE windows_coretemp_load gauge
windows_coretemp_load{core="0",name="Intel Core i7 6700K (Skylake)"} 4
windows_coretemp_load{core="1",name="Intel Core i7 6700K (Skylake)"} 3
windows_coretemp_load{core="2",name="Intel Core i7 6700K (Skylake)"} 5
windows_coretemp_load{core="3",name="Intel Core i7 6700K (Skylake)"} 2
# HELP windows_coretemp_temperature_celsius (Temperature)
# TYPE windows_coretemp_temperature_celsius gauge
windows_coretemp_temperature_celsius{core="0",name="Intel Core i7 6700K (Skylake)"} 36
windows_coretemp_temperature_celsius{core="1",name="Intel Core i7 6700K (Skylake)"} 39
windows_coretemp_temperature_celsius{core="2",name="Intel Core i7 6700K (Skylake)"} 35
windows_coretemp_temperature_celsius{core="3",name="Intel Core i7 6700K (Skylake)"} 35
```

So lets have a discussion about if this is a reasonable approach at all.

I also see the lack of proper temperature reporting has been discussed a number of times already: #495, #560, #650, #539

### CODE REVIEW

**Comment by carlpett** [comment]
Wow, it'd be fantastic to have a working solution for this! But I'm split. On the one hand, there's some precedence in the node_exporter for exposing details about other programs (eg ntp, supervisord), and to some extent this exporter as well (vmware collector is dependent on the VMware guest agent being installed as a WMI provider).
On the other hand, it seems like it is somehow a bit different, and we'd be somewhat committed to maintaining a 3rd party integration.

So not sure, really. Would this be something people would typically be installing on their server fleet?

**Comment by martinlindhe** [comment]
> So not sure, really. Would this be something people would typically be installing on their server fleet?

I doubt it. It's just a quick and dirty solution for the time being.
I guess properly porting the cpu monitoring code from openhardwaremonitor is a more feasible approach.

**Comment by JackGarbiec** [comment]
Just to clarify, do we need to run the actual coretemp binary or download the sdk?

**Comment by JackGarbiec** [comment]
windows_exporter is licensed under MIT, Core Temp seems to only be free for personal use, it needs a commercial license for commercial purposes.

**Comment by martinlindhe** [comment]
> Just to clarify, do we need to run the actual coretemp binary or download the sdk?

Just need the coretemp binary.

**Comment by martinlindhe** [comment]
> windows_exporter is licensed under MIT, Core Temp seems to only be free for personal use, it needs a commercial license for commercial purposes.

Good point, updated original post

**Pull request closed without merging**
