### PR TITLE
add call to set perf counter query

### PR DESCRIPTION
**Pull request by mattdurham**
I believe this has a good chance of fixing https://github.com/prometheus-community/windows_exporter/issues/1373 and https://github.com/prometheus-community/windows_exporter/issues/1374 and https://github.com/prometheus-community/windows_exporter/issues/1371.

### CODE REVIEW

**Comment by jkroepke** [comment]
@JDA88 are you able to test this PR if it resolve the issues?

Here is an pre-built binary to testing based on this PR [windows_exporter.exe.zip](https://github.com/prometheus-community/windows_exporter/files/13865097/windows_exporter.exe.zip)

**Comment by JDA88** [comment]
> @mattdurham Thanks! It seems like we forgot the set an query and seems like an empty query return an default set of metrics only.
> 
> @JDA88 are you able to test this PR if it resolve the issues?

I'll do this ASAP tomorrow morning (East Europe time)

**Comment by mattdurham** [comment]
Tomorrow we should get some additional testing results when the Agent is published also. I made a similar change there.

**Comment by JDA88** [comment]
I tested the version provided and it fixes [#1373](https://github.com/prometheus-community/windows_exporter/issues/1373) and https://github.com/prometheus-community/windows_exporter/issues/1374!

Great find, thanks you for that

**Review by jkroepke — APPROVED** [review]

**Pull request merged**
