### PR TITLE
Ability to disable debug endpoints

### LINKED ISSUE #1424: /net/http/pprof were detected as information disclosure vulnerability
pprof endpoints are exposed by default automatically by net/http/pprof import, which is reported as High security vulnerability by several different vulnerability scanners.

Although we do understand the importance of having pprof endpoints available for debugging/tuning of the exporter, it would be nice to have ability of turning it off completely in production environments (or opt-in to enable it just for debugging).

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes #1424

### CODE REVIEW

**Review by breed808 — APPROVED** [review]
Looks good!

**Comment by maomaoaichirou** [comment]
@jkroepke 
**Is there a sample configuration file for this configuration?**

I specified the parameters but still can't start it？

C:\Users\aw_a_ningcf>C:\windows_exporter\windows_exporter.exe --config.file=C:\windows_exporter\config.yml --debug.enabled=false
windows_exporter.exe: error: unexpected false, try --help

**Comment by jkroepke** [comment]
The frag requires version [v0.26.0-rc.0](https://github.com/prometheus-community/windows_exporter/releases/tag/v0.26.0-rc.0) or higher

**Comment by maomaoaichirou** [comment]
**yes I used the latest version, bug?**

C:\Users\XXXXXX>C:\windows_exporter\windows_exporter.exe --version
windows_exporter, version 0.26.0-tags-v0-26-0-rc-2.1 (branch: heads/tags/v0.26.0-rc.2, revision: 13ebec019572de0ada808f1473dd826cd6a77897)
  build user:       runneradmin@fv-az1212-637
  build date:       20240509-13:37:11
  go version:       go1.21.9
  platform:         windows/amd64
  tags:             unknown

**Comment by maomaoaichirou** [comment]
> **yes I used the latest version, bug?**
> 
> C:\Users\XXXXXX>C:\windows_exporter\windows_exporter.exe --version windows_exporter, version 0.26.0-tags-v0-26-0-rc-2.1 (branch: heads/tags/v0.26.0-rc.2, revision: [13ebec0](https://github.com/prometheus-community/windows_exporter/commit/13ebec019572de0ada808f1473dd826cd6a77897)) build user: runneradmin@fv-az1212-637 build date: 20240509-13:37:11 go version: go1.21.9 platform: windows/amd64 tags: unknown

**Comment by maomaoaichirou** [comment]
@jkroepke 
**yes I used the latest version, bug?**

C:\Users\XXXXXX>C:\windows_exporter\windows_exporter.exe --version
windows_exporter, version 0.26.0-tags-v0-26-0-rc-2.1 (branch: heads/tags/v0.26.0-rc.2, revision: https://github.com/prometheus-community/windows_exporter/commit/13ebec019572de0ada808f1473dd826cd6a77897)
build user: runneradmin@fv-az1212-637
build date: 20240509-13:37:11
go version: go1.21.9
platform: windows/amd64
tags: unknown

**Comment by jkroepke** [comment]
If you looking at --help, the flag is `--[no-]debug.enabled`

`--debug.enabled=false` does not work, but `--no-debug.enabled` works fine. However, the debug endpoints are disabled by default.

**Pull request merged**
