### PR TITLE
Example - Using [defaults] with `--collectors.enabled` argument

### LINKED ISSUE #697: How to use [defaults] in --collectors.enabled flag?
The [flags guidance](https://github.com/prometheus-community/windows_exporter#flags) isn't very clear:

> Comma-separated list of collectors to use. Use [defaults] as a placeholder for all the collectors enabled by default."

I want to have in addition to the defaults `process`, and `container` collectors enabled. Based on the above I thought it should be the following argument:

    --collectors.enabled="[defaults],process,container"

Is this correct?

### PR DESCRIPTION
**Pull request by ramonsmits**
Resolves #697

### CODE REVIEW

**Review by carlpett — APPROVED** [review]
Thanks!

**Comment by carlpett** [comment]
Oh, sorry, one thing missing. You'll need to sign-off the commit, there's some instructions [in the check details](https://github.com/prometheus-community/windows_exporter/pull/698/checks?check_run_id=1703303559)

**Comment by carlpett** [comment]
@ramonsmits I see the +1 reaction, but it still appears to fail the check. Let me know if the instructions are unclear.

**Comment by ramonsmits** [comment]
@carlpett done

**Comment by carlpett** [comment]
Thanks!

**Pull request merged**
