### PR TITLE
CI: Add stale action

### PR DESCRIPTION
**Pull request by jkroepke**
windows_exporter has a lot of opened issue with may not longer interest. I would like to cleanup some of the approx 300 issues and staled PRs.

This action uses https://github.com/actions/stale . After 90 days of inactivity, a post will be written from gh actions. After another 30 days of interactivity, the issue will be closed.

### CODE REVIEW

**Comment by breed808** [comment]
I had considered adding this action some time back, but couldn't decide on appropriate timings. Too low and it adds a burden on users raising the issues, which might discourage users from submitting/updating issues. I also want to avoid this tool resulting in issue duplicates (user creates issue with information, bot closes issue, new user creates new issue missing information from the first issue).

I'd be in favour of introducing this with larger timings, such as 6 months before marking as stale, and a 2-3 month duration before closing issues after that. Does that seem reasonable?

**Comment by jkroepke** [comment]
Them times that I choiced here based on large projects like https://github.com/helm/helm

90/30 that are 3 months + 1 months. I guess there is an inactivity for 3 months, its already stale from my point of view.

Mention that after 120 days of interactivity, users still can post to closed issues and ask for reopen, because the issues are not locked.

special issues can have a lifecycle/frozen label. That excludes tickets from state action.

I feel 180/90 days a bit to long. If the bot posts the stale warning, its unliky that users will posts after 2-3 weeks. Mostly, they react in the first 2 weeks.

**Comment by breed808** [comment]
Just to clarify, would issues closed by this proposed action be locked?

**Comment by jkroepke** [comment]
Example: https://github.com/helm/helm/issues/9293

No locking, just closing.

**Review by breed808 — APPROVED** [review]
OK, as we're not preventing users from re-opening tickets I'm happy to proceed with this.

We can always tweak the timings later depending on user feedback.

**Pull request merged**
