### PR TITLE
codespell: add GH Action for checking spelling issues

### PR DESCRIPTION
**Pull request by mjtrangoni**
Hi @carlpett @breed808,

This add a GH Action for checking spelling issues detected by codespell. As I fixed all of them already at #892, this will prevent us for adding new ones.

### CODE REVIEW

**Comment by breed808** [comment]
Thanks for submitting this!

 I'm thinking we can get #898 reviewed and merged first, then integrate this as a job in the new CI/CD configuration.

**Comment by mjtrangoni** [comment]
There are different approaches, one having only one big config file and other having many smaller ones.

Maybe we can split it in build and linting jobs, but both cases are fine for me.

**Comment by breed808** [comment]
I'm fine with either method as well, so long as dependencies between files can be specified (I.E. build requires lint/testspellcheck jobs to pass before starting).

-------- Original Message --------

**Comment by mjtrangoni** [comment]
Good point!, and it seems this is possible with [workflow_run](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run)

**Comment by breed808** [comment]
@mjtrangoni #898 has been merged, you can rebase this PR on `master` to get the changes.

**Comment by mjtrangoni** [comment]
@breed808 PTAL

**Review by breed808 — APPROVED** [review]
Looks good! Thanks for this :+1:

**Pull request merged**
