### PR TITLE
Restore Windows 2012 support.

### LINKED ISSUE #1443: in windows server 2012 r2 datacenter, the windows_exporter-0.25.1-amd64.exe has exception "the system cannot find the file specified"
when I deploy the node exporter in windows server 2012 r2 datacenter, the performance metrics is not completed
and submit an exception "the system cannot find the file specified",
because in the 2012 system there's no register key "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\UBR"
when I add the UBR key and value of 104a, the problem is resolved

the register key's type is REG_DWORD 32bit

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes #1443

### CODE REVIEW

**Review by breed808 — APPROVED** [review]
:+1:

**Comment by chinaxushi** [comment]
Very much looking forward to it

**Comment by jkroepke** [comment]
@chinaxushi A pre-built version is availible here: https://github.com/prometheus-community/windows_exporter/actions/runs/8767881067/artifacts/1432390524

Would it be possible, that you can test it? It may take some time for me to get an Windows Server 2012 environment.

**Comment by chinaxushi** [comment]
I have already replied to the test results in the #1426

**Pull request merged**
