### PR TITLE
cs: Deprecate collector + os: Deprecate metrics [memory metrics moved to `memory` collector] (click PR for more information)

### LINKED ISSUE #1593: logical processor metric output is not matching  with server
### Current Behavior

windows exporter
windows_cs_logical_processors is showing count as 24 but actual in server is 152

### Expected Behavior

logical processors is 152

### Steps To Reproduce

```Markdown
Get-WmiObject -class Win32_processor | ft NumberOfCores,NumberOfLogicalProcessors
```

### Environment

- windows_exporter Version: 0.25.1
- Windows Server Version: windows server 2019

### windows_exporter logs

```shell
count mismatch
```

### Anything else?
processor details
processor details_powershell
processor details_using_cpu_metric

processor details_cs_logical_metric

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes #1593

## cs collector metrics

The metrics still exists, but moved to other collectors,

| Old Metric | New Metric |
|--------|--------|
| `windows_cs_hostname`| `windows_os_hostname`|
| `windows_cs_physical_memory_bytes` | `windows_memory_physical_free_bytes` |
| `windows_cs_logical_processors`  |  `windows_cpu_logical_processor` |

## os collector metrics

| Old Metric | New Metric |
|--------|--------|
| `windows_os_time`| `windows_time_current_timestamp_seconds`|
| `windows_os_timezone` | `windows_time_timezone` |
| `windows_os_users`  |  `count(windows_logon_logon_type)`|
| `windows_os_physical_memory_free_bytes`| `windows_memory_physical_free_bytes`  |
| `windows_os_process_memory_limit_bytes` | `windows_memory_process_memory_limit_bytes` |
| `windows_os_virtual_memory_free_bytes` | `windows_memory_commit_limit - windows_memory_committed_bytes` | 
| `windows_os_visible_memory_bytes` | `windows_memory_physical_total_bytes`  | 
| `windows_os_virtual_memory_bytes` | `windows_memory_commit_limit ` | 
| `windows_os_processes_limit` | `windows_system_process_limit`  | 
| `windows_os_processes` | `windows_system_processes` |

### CODE REVIEW

**Comment by jacbo0112** [comment]
This action has a significant impact

**Comment by jkroepke** [comment]
> This action has a significant impact

@jacbo0112 I'm aware of this. And I this PR does not remove any metrics. The old metrics remains. It's not an breaking change.

Only the documentation for the old metrics will be disappear.

**Comment by jacbo0112** [comment]
> > 此操作具有重大影响
> 
> 我知道这一点。而且我这个 PR 没有删除任何指标。旧指标仍然存在。这不是一个突破性的变化。我对其他不太重要的收藏家进行重大更改。但对于核心指标，我将保留一些宽限期。
> 
> 只有旧指标的文档才会消失并标记为已弃用。计划在 2025 年年中移除它们。
> 
> 但在此导出程序达到 1.0 之前，某些操作是强制性的。
> 
> 有一个 cs 收集器，用于公开 cpu 和内存指标。有一个 OS 收集器，用于公开内存指标。还有一个 memory metrics 公开了 metrics。
> 
> 这是混乱的。

There are no issues with the corresponding product design. It is important to carefully consider changes in indicator names and confirm them all at once after careful consideration to avoid repeated name changes in the future

**Comment by jacbo0112** [comment]
My understanding of the windows_time collector is that it is used to obtain Windows time service metrics. But window_os_time checks the Windows time. Windows_os_timezone is used to view the time zone of Windows. Will migrating these two metrics to the Windows time collector result in only requiring the operating system's time and time zone, and requiring a separate collector to be enabled

**Comment by jkroepke** [comment]
Thats fully correct. Any time related metric is now inside time collector. The scope is increased. If you care about time on your system, you might be interest into time service metrics as well. If you need the timezone metric, you habe to enable time collector. Thats the design choice. Splitt large generic collector.

Another example is the process_count: It information was collected (but not exposed) in the system collector as well, while the thread count metrics remains on system collector.

The paging information inside the os collector will be moved to an separated paging collector as well.

**Comment by w1mm3r** [comment]
Please update the table above
windows_cs_physical_memory_bytes should be replaced by windows_memory_physical_total_bytes
I had to redo the changes to my dashboards.

**Pull request merged**
