### PR TITLE
Add HTTPS configuration

### PR DESCRIPTION
**Pull request by SuperQ**
Add the exporter-toolkit https package to allow configuring TLS and
auth.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
Simplified version of https://github.com/prometheus-community/windows_exporter/pull/680

**Comment by carlpett** [comment]
I wonder why the promu logs don't seem to output the actual errors in builds on AppVeyor... Anyway, the build fails because of an undefined variable (`logger`), which I guess was left as a TODO to integrate?

**Comment by shubhampal288** [comment]
I just tested the code on my system and I see that I am unable to use --web.config as "windows_exporter.exe: error: unknown long flag '--web.config', try --help", can @SuperQ explain this?

**Comment by replay** [comment]
>  the build fails because of an undefined variable (logger), which I guess was left as a TODO to integrate?

I think the issue is that `https.Listen()` requires a `go-kit` logger, but the windows exporter currently uses `logrus` (via `github.com/prometheus/common/log`).

So we'd have to either replace the logger used by the `windows_exporter` and make it use `go-kit` everywhere, or we just instantiate a `go-kit` logger to pass into `https.Listen()` which means we'll end up with mixed loggers.

**Comment by carlpett** [comment]
So, PR is updated with working logging. I also took this opportunity to copy `common/log` into a new package `log` in the exporter, as discussed previously @breed808.

**Comment by replay** [comment]
> So, PR is updated with working logging. I also took this opportunity to copy common/log into a new package log in the exporter, as discussed previously @breed808.

Thanks a lot @carlpett for implementing that 👍.
I'd be happy to review it, unfortunately my approval won't be sufficient to merge this PR as far as I understand.

**Comment by breed808** [comment]
I've tested this with a self-signed CA and certificate, and it's looking good :+1:
Do we want additional testing or review on this change?

**Comment by carlpett** [comment]
Whoops, missed the response! Yeah, my testing looked good as well, so I think we can get it out there for some feedback. It's marked as experimental, after all.
I can't approve PRs I've contributed to though, so if you think it looks good I'll need a thumbs up there :slightly_smiling_face:

**Comment by hartman17** [comment]
We are willing to test this on a larger scale once it's merged and a release is cut. Providing any feedback/issues we encounter.

**Review by breed808 — APPROVED** [review]
> I can't approve PRs I've contributed to

I wasn't aware of this limitation, but it makes sense. PR looks good to me :+1:

**Pull request merged**
