### PR TITLE
Add additional metrics to the ADFS collector

### PR DESCRIPTION
**Pull request by akrauza**

### CODE REVIEW

**Comment by akrauza** [comment]
Retracting PR

**Comment by akrauza** [comment]
@breed808 Hey Ben! I closed out this PR because I am getting a DSO conflict error (https://github.com/prometheus-community/windows_exporter/runs/4704063323) with a commit (`sha: 9206245`) that was made by Calle Pettersson where their Sign Off doesn't match their registered email. What would the best course of action be here? I tried to do an edit of that commit, but that did't seem to help. Please let me know. Thanks!

**Comment by breed808** [comment]
This almost looks like you've merged the `master` branch into your `more-adfs-metrics` branch, but there's no merge commit.

You could run `rebase -i master` from your branch and drop the commits that are already in master:
Rebase of feature branch onto master

**Comment by akrauza** [comment]
I believe it was a result of be doing a bad rebase earlier. I have figured out my mistake and opened a separate PR for your review ( #909 )

**Pull request closed without merging**
