### PR TITLE
replace these deprecated functions

### PR DESCRIPTION
**Pull request by yangliyl**
replace these prometheus deprecated functions

### CODE REVIEW

**Review by breed808 — APPROVED** [review]
Thanks for submitting this! You'll need to rebase the feature branch to pick up some recent CI fixes.

**Comment by yangliyl** [comment]
Is it okay now? @breed808

**Comment by breed808** [comment]
I think something's gone wrong in the rebase; the PR is attempting to merge all recent commits rather than the previous single commit.

When switched to your feature branch, does `git rebase master` make any changes? Alternatively you can run `git rebase -i master` to perform the rebase interactively.

**Comment by breed808** [comment]
Thanks, that's looking good now :+1:

**Pull request merged**
