### PR TITLE
Run CI on pushes to master branch

### LINKED ISSUE #940: Builds are not triggered on main branch so container image isn't produced
In https://github.com/prometheus-community/windows_exporter/pull/864 some logic was added to build a "bleeding edge" container:

https://github.com/prometheus-community/windows_exporter/blob/5106b829c3092ef3f1346790336ba0789ef30c01/.github/workflows/ci.yml#L180-L185

This doesn't trigger currently because the workflow only runs on PR's and tags:

https://github.com/prometheus-community/windows_exporter/blob/5106b829c3092ef3f1346790336ba0789ef30c01/.github/workflows/ci.yml#L5-L12

Adding a trigger like 

```
on:
  push:
    branches: [ master ]
``` 

would build, test and then push the bleeding edge image as well give a signal that main branch is healthy after the PR merge. @breed808 @carlpett  any thoughts on this?

### PR DESCRIPTION
**Pull request by breed808**
Required to keep container image (with "latest" tag) up to date. Will
also ensure the master branch is healthy after PR merges.

Resolves #940

### CODE REVIEW

**Comment by jsturtevant** [comment]
lgtm

**Comment by breed808** [comment]
@jsturtevant I've amended the commit to perform the GCR login on push as well, preventing the image push from failing on a `master` build.

**Comment by jsturtevant** [comment]
good catch!

**Comment by breed808** [comment]
Apologies for the notification spam from all the commits/pushes. I've identified a timing issue with the Promtool job, where the script queries the exporter before it is ready.

I've also set the Promtool job to run the exporter on a different port, in the event that both exporters (e2e and promtool) are running at the same time.

**Comment by breed808** [comment]
The promtool job failures are affecting other PRs, such as #943, so I'll merge this one now.
@carlpett when you get to this in your notifications, let me know if this needs revisiting.

**Pull request merged**
