### PR TITLE
Add Win32_DiskDrive Collector

### PR DESCRIPTION
**Pull request by 6fears7**
PR to retrieve general disk information and health from [Win32_DiskDrive](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-diskdrive).

Metrics:

- 	DiskInfo     
- 	Status       
- 	Size         
- 	Partitions   
- 	Availability 

```
Benchmark results:
goos: windows
goarch: amd64
pkg: github.com/prometheus-community/windows_exporter/collector
cpu: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
BenchmarkDiskDriveCollector-8   	       1	1334272800 ns/op	41182008 B/op	  125688 allocs/op
PASS
ok  	github.com/prometheus-community/windows_exporter/collector	4.943s
```

My tests did not have any servers where "Availability" returned any data, so if there are those who do have that for testing, that would be sublime. 

Run the collector with `--collectors.enabled="disk_drive"`

Preview:
image

### CODE REVIEW

**Review by 6fears7 — COMMENTED** [review]
Fixed metric type and naming

**Review by breed808 — COMMENTED** [review]
Apologies, I must have accidentally marked this as read in my inbox.

Collector looks good, all that's missing is documentation (new file in `docs/` and a collector entry in the project README.

**Comment by 6fears7** [comment]
Not an issue. I should have it by Monday.

**Comment by 6fears7** [comment]
Signed off, apologies.

**Review by breed808 — APPROVED** [review]
Looks good, thanks for updating the PR :+1:

**Pull request merged**
